package Model;
// Generated 19 sept. 2024 10:48:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name="compte"
    ,catalog="criminels"
)
public class Compte extends BaseModel implements java.io.Serializable {


     private String password;
     private String type;
     private String username;

    public Compte() {
    }

    public Compte(String password, String type, String username) {
       this.password = password;
       this.type = type;
       this.username = username;
    }
   


    
    @Column(name="password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="username", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


