package Model;
// Generated 19 sept. 2024 10:48:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Identite generated by hbm2java
 */
@Entity
@Table(name="identite"
    ,catalog="criminels"
)
public class Identite extends BaseModel implements java.io.Serializable {


  
     private String adresseActuelle;
     private String adresseEmail;
     private String adressePrecedent;
     private String antecedentJudiciaires;
     private String associerOuComplice;
     private String comportementParticuliere;
     private String condamnation;
     private String couleurCheveux;
     private String couleurYeux;
     private String dateFraction;
     private String dateNaissance;
     private String infractions;
     private String lieuInfraction;
     private String lieuNaissance;
     private String modeOperatoire;
     private String nationalite;
     private String niveauEducation;
     private String nom;
     private String numeroTelephone;
     private String paoids;
     private String prenom;
     private String professionActuelle;
     private String sexe;
     private String signesParticuliere;
     private String situationFamiliale;
     private String taille;

    public Identite() {
    }

    public Identite(String adresseActuelle, String adresseEmail, String adressePrecedent, String antecedentJudiciaires, String associerOuComplice, String comportementParticuliere, String condamnation, String couleurCheveux, String couleurYeux, String dateFraction, String dateNaissance, String infractions, String lieuInfraction, String lieuNaissance, String modeOperatoire, String nationalite, String niveauEducation, String nom, String numeroTelephone, String paoids, String prenom, String professionActuelle, String sexe, String signesParticuliere, String situationFamiliale, String taille) {
       this.adresseActuelle = adresseActuelle;
       this.adresseEmail = adresseEmail;
       this.adressePrecedent = adressePrecedent;
       this.antecedentJudiciaires = antecedentJudiciaires;
       this.associerOuComplice = associerOuComplice;
       this.comportementParticuliere = comportementParticuliere;
       this.condamnation = condamnation;
       this.couleurCheveux = couleurCheveux;
       this.couleurYeux = couleurYeux;
       this.dateFraction = dateFraction;
       this.dateNaissance = dateNaissance;
       this.infractions = infractions;
       this.lieuInfraction = lieuInfraction;
       this.lieuNaissance = lieuNaissance;
       this.modeOperatoire = modeOperatoire;
       this.nationalite = nationalite;
       this.niveauEducation = niveauEducation;
       this.nom = nom;
       this.numeroTelephone = numeroTelephone;
       this.paoids = paoids;
       this.prenom = prenom;
       this.professionActuelle = professionActuelle;
       this.sexe = sexe;
       this.signesParticuliere = signesParticuliere;
       this.situationFamiliale = situationFamiliale;
       this.taille = taille;
    }
   


    
    @Column(name="adresseActuelle")
    public String getAdresseActuelle() {
        return this.adresseActuelle;
    }
    
    public void setAdresseActuelle(String adresseActuelle) {
        this.adresseActuelle = adresseActuelle;
    }

    
    @Column(name="adresseEmail")
    public String getAdresseEmail() {
        return this.adresseEmail;
    }
    
    public void setAdresseEmail(String adresseEmail) {
        this.adresseEmail = adresseEmail;
    }

    
    @Column(name="adressePrecedent")
    public String getAdressePrecedent() {
        return this.adressePrecedent;
    }
    
    public void setAdressePrecedent(String adressePrecedent) {
        this.adressePrecedent = adressePrecedent;
    }

    
    @Column(name="antecedentJudiciaires")
    public String getAntecedentJudiciaires() {
        return this.antecedentJudiciaires;
    }
    
    public void setAntecedentJudiciaires(String antecedentJudiciaires) {
        this.antecedentJudiciaires = antecedentJudiciaires;
    }

    
    @Column(name="associerOuComplice")
    public String getAssocierOuComplice() {
        return this.associerOuComplice;
    }
    
    public void setAssocierOuComplice(String associerOuComplice) {
        this.associerOuComplice = associerOuComplice;
    }

    
    @Column(name="comportementParticuliere")
    public String getComportementParticuliere() {
        return this.comportementParticuliere;
    }
    
    public void setComportementParticuliere(String comportementParticuliere) {
        this.comportementParticuliere = comportementParticuliere;
    }

    
    @Column(name="Condamnation")
    public String getCondamnation() {
        return this.condamnation;
    }
    
    public void setCondamnation(String condamnation) {
        this.condamnation = condamnation;
    }

    
    @Column(name="couleurCheveux")
    public String getCouleurCheveux() {
        return this.couleurCheveux;
    }
    
    public void setCouleurCheveux(String couleurCheveux) {
        this.couleurCheveux = couleurCheveux;
    }

    
    @Column(name="couleurYeux")
    public String getCouleurYeux() {
        return this.couleurYeux;
    }
    
    public void setCouleurYeux(String couleurYeux) {
        this.couleurYeux = couleurYeux;
    }

    
    @Column(name="dateFraction")
    public String getDateFraction() {
        return this.dateFraction;
    }
    
    public void setDateFraction(String dateFraction) {
        this.dateFraction = dateFraction;
    }

    
    @Column(name="dateNaissance")
    public String getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(String dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    
    @Column(name="infractions")
    public String getInfractions() {
        return this.infractions;
    }
    
    public void setInfractions(String infractions) {
        this.infractions = infractions;
    }

    
    @Column(name="lieuInfraction")
    public String getLieuInfraction() {
        return this.lieuInfraction;
    }
    
    public void setLieuInfraction(String lieuInfraction) {
        this.lieuInfraction = lieuInfraction;
    }

    
    @Column(name="lieuNaissance")
    public String getLieuNaissance() {
        return this.lieuNaissance;
    }
    
    public void setLieuNaissance(String lieuNaissance) {
        this.lieuNaissance = lieuNaissance;
    }

    
    @Column(name="modeOperatoire")
    public String getModeOperatoire() {
        return this.modeOperatoire;
    }
    
    public void setModeOperatoire(String modeOperatoire) {
        this.modeOperatoire = modeOperatoire;
    }

    
    @Column(name="nationalite")
    public String getNationalite() {
        return this.nationalite;
    }
    
    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }

    
    @Column(name="niveauEducation")
    public String getNiveauEducation() {
        return this.niveauEducation;
    }
    
    public void setNiveauEducation(String niveauEducation) {
        this.niveauEducation = niveauEducation;
    }

    
    @Column(name="nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="numeroTelephone")
    public String getNumeroTelephone() {
        return this.numeroTelephone;
    }
    
    public void setNumeroTelephone(String numeroTelephone) {
        this.numeroTelephone = numeroTelephone;
    }

    
    @Column(name="paoids")
    public String getPaoids() {
        return this.paoids;
    }
    
    public void setPaoids(String paoids) {
        this.paoids = paoids;
    }

    
    @Column(name="prenom")
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="professionActuelle")
    public String getProfessionActuelle() {
        return this.professionActuelle;
    }
    
    public void setProfessionActuelle(String professionActuelle) {
        this.professionActuelle = professionActuelle;
    }

    
    @Column(name="sexe")
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="signesParticuliere")
    public String getSignesParticuliere() {
        return this.signesParticuliere;
    }
    
    public void setSignesParticuliere(String signesParticuliere) {
        this.signesParticuliere = signesParticuliere;
    }

    
    @Column(name="situationFamiliale")
    public String getSituationFamiliale() {
        return this.situationFamiliale;
    }
    
    public void setSituationFamiliale(String situationFamiliale) {
        this.situationFamiliale = situationFamiliale;
    }

    
    @Column(name="taille")
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }




}


